language: php

os:
  - linux

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
    - composer self-update
    - composer install

script: php vendor/codeception/codeception/codecept run
